---
- hosts: all
  become: true
  vars:
    ansible_user: ec2-user
  tasks:
    - name: Wait for SSH to come up
      wait_for_connection:
        delay: 30
        sleep: 5
        timeout: 300

    - name: Install Docker
      ansible.builtin.command: amazon-linux-extras install -y docker

    - name: Install docker-compose
      ansible.builtin.command: pip3 install docker-compose
    
    - name: Enable docker
      ansible.builtin.command: systemctl enable docker

    - name: Start docker
      ansible.builtin.command: service docker start

    - name: Add group
      ansible.builtin.command: usermod -a -G docker ec2-user
    
    - name: Pull package
      ansible.builtin.command: docker pull ghcr.io/yisu12/hello-2048:latest

    - name: Download docker-compose.yml
      ansible.builtin.command: wget https://raw.githubusercontent.com/Yisu12/hello-terraform/main/docker-compose.yml

    - name: Run image
      ansible.builtin.command: docker-compose up -d
