---
- hosts: all
  gather_facts: no
  become: true
  vars:
    ansible_user: ec2-user
  tasks:
    - name: Wait for SSH to come up
      wait_for_connection:
        delay: 30
        sleep: 5
        timeout: 300

    - name: Install Docker
      command: amazon-linux-extras install -y docker

    - name: Install docker-compose
      pip:
        name: docker-compose
        executable: pip3

    - name: Start and enable docker
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Add ec2-user to group
      user:
        name: ec2-user
        group: docker
   
    - name: Pull package
      command: docker pull ghcr.io/yisu12/hello-terraform:latest

    - name: Copy docker-compose
      copy:
        src: ./docker-compose.yml
        dest: /home/ec2-user
        owner: ec2-user
        group: ec2-user
        mode: "0644"
        directory_mode: "0755"
          
    - name: Run container
      shell:
        cmd: "/usr/local/bin/docker-compose up -d"
        chdir: /home/ec2-user
