---
- hosts: all
  gather_facts: false
  tasks:
    - name: Wait for SSH to come up
      wait_for_connection:
        delay: 10
        sleep: 5
        timeout: 300
      vars:
        ansible_user: ec2-user

- hosts: all
  vars:
    ansible_user: ec2-user
  tasks:
    - name: Install httpd
      ansible.builtin.yum:
        name: httpd
        update_cache: yes
      become: true
    - name: Enable httpd
      ansible.builtin.service:
        name: httpd
        enabled: true
        state: started
      become: true
    - name: Copy app
      copy:
        src: ../hello-2048/public_html/
        dest: /var/www/html/
        owner: apache
        group: apache
        mode: "0644"
        directory_mode: "0755"
      become: true
