---
- hosts: all
  gather_facts: no
  become: true
  vars:
    ansible_user: ec2-user
  tasks:
    - name: Wait for SSH to come up
      wait_for_connection:
        delay: 30
        sleep: 5
        timeout: 300

    - name: Install Docker
      yum:
        name: docker

    - name: Install docker-compose
      pip:
        name: docker-compose>1.7.0,<2.0.0
        executable: pip3

    - name: Start and enable docker
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Add ec2-user to group
      user:
        name: ec2-user
        group: docker

    - name: Copy docker-compose
      copy:
        src: ../docker/docker-compose.yml
        dest: /home/ec2-user
        owner: ec2-user
        group: ec2-user
        mode: "0644"
        directory_mode: "0755"
          
    - name: Pull image and run it
      community.docker.docker_compose:
        project_src: /home/ec2-user/
        pull: true
      vars:
        ansible_python_interpreter: /usr/bin/python3
